name: Debug
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: jp-lopez/github-actions-debug@main
        with:
          jq_selector: ".pull_request"